server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: bookauthorcatalog
        uri: http://localhost:8082/
        predicates:
        - Path=/bookauthorcatalog/**
      - id: shopping
        uri: http://localhost:8086/
        predicates:
        - Path=/onlineshopping/**
